In [17]:
import math

import numpy as np

### Массовое обслуживание без вероятностей выйти из очереди


In [18]:
lmb = 15
mu = 5
query = 4
ops = 3


In [19]:
p_0 = 1 / (
    1 +
    sum([lmb ** k / ((mu ** k) * math.factorial(k)) for k in range(1, ops + 1)]) +
    sum([lmb ** k / (math.factorial(ops) * (mu ** k) * (ops ** (k - ops))) for k in range(ops + 1, ops + query + 1)])
        )
def p_i(i):
    if i > ops:
        return (lmb ** i) * p_0 / (math.factorial(ops) * (mu ** i) * (ops ** (i - ops)))
    else:
        return (lmb ** i) * p_0 / ((mu ** i) * math.factorial(i))

print(p_0, p_i(7))

0.03225806451612903 0.14516129032258066


### Марковская цепь с дискретным временем

In [20]:
m = 5
matrix = [[0 for i in range(m)] for j in range(m)]
matrix[0][1] = 0.6
matrix[1][2] = 0.2
matrix[2][3] = 0.3
matrix[3][4] = 0.4
matrix[4][0] = 0.5
# matrix = [[]]
for i in range(m):
    matrix[i][i] = 1 - sum(matrix[i])
print(np.array(matrix))

[[0.4 0.6 0.  0.  0. ]
 [0.  0.8 0.2 0.  0. ]
 [0.  0.  0.7 0.3 0. ]
 [0.  0.  0.  0.6 0.4]
 [0.5 0.  0.  0.  0.5]]


In [22]:
import numpy.linalg as la
SLAU = np.empty((m, m))
b = np.empty(m)
for i in range(m - 1):
    for j in range(m):
        SLAU[i, j] = matrix[j][i]
    b[i] = 0
    SLAU[i, i] -= 1
# normalizing
for i in range(m):
    SLAU[-1, i] = 1
b[-1] = 1
print("SLAU:", SLAU)
print("b:", b)

stationary_probs = la.solve(SLAU, b)
print(stationary_probs)

SLAU: [[-0.6  0.   0.   0.   0.5]
 [ 0.6 -0.2  0.   0.   0. ]
 [ 0.   0.2 -0.3  0.   0. ]
 [ 0.   0.   0.3 -0.4  0. ]
 [ 1.   1.   1.   1.   1. ]]
b: [0. 0. 0. 0. 1.]
[0.11494253 0.34482759 0.22988506 0.17241379 0.13793103]


### Игра с двумя игроками

In [ ]:
p = 1/3 
q = 1 - p
A = 100
B = 130

In [ ]:
import numpy.linalg as la
SLAU = np.empty((m, m))
b = np.empty(m)
for i in range(A + B):
    if i == A:
        a = 0

### Гибель, рождение

In [23]:
lmb = 1
mu = 1
N = 500
pi_0 = (1 + lmb/mu) ** (-N)
def pi_i(i):
    return pi_0 * (lmb/mu) ** i