In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
b = 1 + 0.1*(52 - 53)
N = 4

In [6]:
matrix = np.array([[10*b, 1, 2, 3],
                   [1, 10*b, -3, 2],
                   [2, -3, 10*b, 1],
                   [3, 2, 1, 10*b]])
initial_matrix = matrix.copy()
np.set_printoptions(precision=3)

def index_max_el(matrix: np.ndarray) -> tuple:
    max_value = None
    max_index = (-1, -1)

    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if i != j:
                if max_value is None or abs(matrix[i][j]) > max_value:
                    max_value = abs(matrix[i][j])
                    max_index = (i, j)
    
    return max_index

In [7]:
row_indices, col_indices = np.indices(matrix.shape)
non_diagonal_mask = row_indices != col_indices
initial_vectors = np.eye(matrix.shape[0])
iteration = 1

while np.abs(matrix[non_diagonal_mask]).max() > 0.01:
    print("итерация:", iteration)
    iteration += 1
    alpha, beta = index_max_el(matrix)
    
    rotate_matrix = np.eye(matrix.shape[0])
    phi = 1/2*(np.pi / 2 - np.arctan((matrix[alpha][alpha] - matrix[beta][beta])/2/matrix[alpha][beta]))
    
    rotate_matrix[alpha][alpha] = np.cos(phi)
    rotate_matrix[beta][beta] = np.cos(phi)
    rotate_matrix[alpha][beta] = -np.sin(phi)
    rotate_matrix[beta][alpha] = np.sin(phi)
    print("матрица поворота: \n", rotate_matrix)
    initial_vectors = (initial_vectors @ rotate_matrix).copy()
    
    matrix = (rotate_matrix.T @ matrix @ rotate_matrix).copy()
    print("матрица A после преобразования: \n", matrix)

print("Полученная диагональная матрица с собственными значениями:\n", matrix)
print("Полученная матрица после перемножения матриц Q:\n", initial_vectors)

итерация: 1
матрица поворота: 
 [[ 0.707  0.     0.    -0.707]
 [ 0.     1.     0.     0.   ]
 [ 0.     0.     1.     0.   ]
 [ 0.707  0.     0.     0.707]]
матрица A после преобразования: 
 [[ 1.200e+01  2.121e+00  2.121e+00  2.461e-16]
 [ 2.121e+00  9.000e+00 -3.000e+00  7.071e-01]
 [ 2.121e+00 -3.000e+00  9.000e+00 -7.071e-01]
 [ 1.231e-16  7.071e-01 -7.071e-01  6.000e+00]]
итерация: 2
матрица поворота: 
 [[ 1.     0.     0.     0.   ]
 [ 0.     0.707 -0.707  0.   ]
 [ 0.     0.707  0.707  0.   ]
 [ 0.     0.     0.     1.   ]]
матрица A после преобразования: 
 [[ 1.200e+01  3.000e+00  6.153e-17  2.461e-16]
 [ 3.000e+00  6.000e+00  1.231e-16  4.266e-17]
 [ 6.153e-17  2.461e-16  1.200e+01 -1.000e+00]
 [ 1.231e-16  4.266e-17 -1.000e+00  6.000e+00]]
итерация: 3
матрица поворота: 
 [[ 0.924 -0.383  0.     0.   ]
 [ 0.383  0.924  0.     0.   ]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]
матрица A после преобразования: 
 [[ 1.324e+01  4.903e-16  1.039e-16  2.437e-16]
 [

In [5]:
i = 0
q = initial_vectors[:, i]
#print(initial_matrix, q)
print(initial_matrix @ q, matrix[i][i] * q, sep="\n")
print(initial_matrix @ q - matrix[i][i] * q)

[8.65117194 3.58343275 3.58343275 8.65117194]
[8.65117194 3.58343275 3.58343275 8.65117194]
[1.77635684e-15 0.00000000e+00 0.00000000e+00 1.77635684e-15]
