In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random
from graph_tools import plot_graph, find_stationary_matrices

### Задание
![Задание](marketing_task.png)

In [2]:
random.seed(0)
k = 3
i = 3
j = 3
p = np.random.rand(3, 3, 3)
p = -np.sort(-p)
p = p[:, :, np.arange(k)] / np.sum(p, axis=2, keepdims=True)

R = np.random.rand(3, 3, 3)
R = -np.sort(-R)
R = R[:, :, np.arange(k)] / np.sum(R, axis=2, keepdims=True)
r = 270*R + 30

c = 20 * np.random.rand(3) + 10
c = -np.sort(-c)
beta = np.random.rand(1)

### Постановка задачи
![Задание](Общая_задача.png)

In [3]:
print(R[2, :, :])
print(r[2, :, :])

[[0.60775694 0.26916512 0.12307794]
 [0.5203947  0.37614385 0.10346145]
 [0.71728065 0.23682743 0.04589192]]
[[194.0943736  102.67458258  63.23104382]
 [170.50656887 131.5588386   57.93459252]
 [223.66577565  93.94340649  42.39081786]]


### Неуправляемый режим (k = 3)

In [4]:
P = p[2, :, :]
R_2 = R[2, :, :]
r_2 = r[2, :, :]
c_2 = c[2]
#plot_graph(P, "Вероятности перехода между i-ми состояниями")
#plot_graph(R_2, "Вероятности получения дохода", states=["Отличный", "средний", "посредственный"])

### Управляемый режим
![Задание](Алгоритм_полного_перебора.png)

In [11]:
v_k_i = np.sum(p * r, axis=2)
print(v_k_i)
pi_k = find_stationary_matrices(p)
pi_k = pi_k[:, 1, :].reshape((3, 3))

print(pi_k)
E = np.sum(v_k_i * pi_k, axis=1)
print(E)

[[123.46294551 136.73480537 123.21545923]
 [146.53668898 157.60339701 142.64056137]
 [130.39304781 158.36480809 179.94643222]]
[[0.54819565 0.39211666 0.05968769]
 [0.53405761 0.36673585 0.09920653]
 [0.54171643 0.3188643  0.13941927]]
[128.65229101 150.2087263  146.22094033]
