In [49]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random
from graph_tools import plot_graph

In [50]:
random.seed(0)
k = 3
i = 3
j = 3
p = np.random.rand(3, 3, 3)
p = -np.sort(-p)
p = p[:, :, np.arange(k)] / np.sum(p, axis=2, keepdims=True)

R = np.random.rand(3, 3, 3)
R = -np.sort(-R)
R = R[:, :, np.arange(k)] / np.sum(R, axis=2, keepdims=True)
r = 270*R + 30

c = 20 * np.random.rand(3) + 10
c = -np.sort(-c)
beta = np.random.rand(1)

In [51]:
print(R[2, :, :])
print(r[2, :, :])

[[0.66487337 0.20476381 0.13036282]
 [0.39877865 0.31075829 0.29046305]
 [0.37941251 0.32728926 0.29329824]]
[[209.51580874  85.28622907  65.19796219]
 [137.67023683 113.904739   108.42502417]
 [132.44137738 118.36809888 109.19052374]]


### Неуправляемый режим (k = 3)

In [52]:
P = p[2, :, :]
R_2 = R[2, :, :]
r_2 = r[2, :, :]
c_2 = c[2]
plot_graph(P, "Вероятности перехода между i-ми состояниями")
plot_graph(R, "Вероятности получения дохода", states=[f"Отличный {}"])

SyntaxError: f-string: valid expression required before '}' (3862607685.py, line 6)