In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A  = np.linspace(0.2, 2.2, 41)
B = (A[1:] + A[:-1]) / 2


In [ ]:
n = 63
N = 3
def f(t, x):
    return (2*N + 3)/(N + 2) * (n - 58) * np.sin((n - 58)*(3*(n - 7) + 3)/((N + 7) * t) * x)

In [ ]:
x0 = 0.2
u0 = 3

In [3]:
A = np.array([[1, 2], [2, 0]])
B = np.array([[1, 1], [3, 0]])
C = np.array([[3, 1], [2, 1]])
D = np.array([[2, 3], [1, 0]])
Q = np.array([[1, 1], [0, 4]])

T = np.array([[7, 1], [2, 2]])
K = np.array([[4, 6], [5, 6]])

print(A@T@K@B.T)

[[165 207]
 [162 198]]


In [4]:
print(B@T@T)

[[ 69  15]
 [153  27]]


In [5]:
print(C@A@D.T)

[[28  5]
 [20  4]]
